# Generated by Django 5.1.2 on 2024-11-06 21:10

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Criação do grupo Administrador
    admin_group, created = Group.objects.get_or_create(name='Administrador')
    if created:
        admin_permissions = Permission.objects.all() 
        admin_group.permissions.set(admin_permissions)
        

    # Criação do grupo Leitor
    reader_group, created = Group.objects.get_or_create(name='Leitor')
    if created:
        permissions = Permission.objects.filter(
            codename__in=[
                'add_emprestimo',  
                'view_emprestimo', 
                'view_livro',      
            ]
        )
        reader_group.permissions.set(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_options"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
