# Generated by Django 5.1.2 on 2024-10-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livro",
            options={
                "ordering": ["titulo"],
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
    ]
