# Generated by Django 5.1.2 on 2024-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_alter_livro_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="isbn",
            field=models.CharField(
                blank=True, max_length=13, unique=True, verbose_name="ISBN"
            ),
        ),
    ]
