# Generated by Django 5.1.2 on 2024-11-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0004_alter_livro_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="capa",
            field=models.ImageField(
                blank=True, null=True, upload_to="capas/", verbose_name="Capa do Livro"
            ),
        ),
    ]
