# Generated by Django 5.1.2 on 2024-11-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0006_alter_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
