# Generated by Django 5.1.2 on 2024-11-03 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("livros", "0004_alter_livro_isbn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_emprestimo",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Empréstimo"
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Devolução"
                    ),
                ),
                (
                    "data_prevista_devolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Prevista de Devolução"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Em análise", "Em análise"),
                            ("Emprestado", "Emprestado"),
                            ("Recusado", "Recusado"),
                            ("Finalizado", "Finalizado"),
                        ],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="emprestimos/capas/",
                        verbose_name="Capa do Livro",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livros.livro",
                        verbose_name="Livro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
                "ordering": ["data_emprestimo"],
            },
        ),
    ]
