# Generated by Django 5.1.2 on 2024-11-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emprestimo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emprestimo",
            name="capa",
        ),
    ]
