# Generated by Django 5.1.2 on 2024-11-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprestimo", "0002_remove_emprestimo_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
    ]
